import { SynthSettings } from "./types";

export const presets: Record<string, SynthSettings> = {
  "Classic Moog": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 7,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.4,
        detune: -7,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1000,
      resonance: 0.5,
      contourAmount: 0.5,
      type: "lowpass",
    },
    envelope: {
      attack: 0.1,
      decay: 0.3,
      sustain: 0.7,
      release: 0.5,
    },
    lfo: {
      rate: 5,
      depth: 0.3,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 0,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "New Moog": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "triangle",
        frequency: 0,
        range: "4",
        volume: 0.7,
        detune: 0,
        pan: 0,
      },
      {
        waveform: "triangle",
        frequency: 0,
        range: "4",
        volume: 0.7,
        detune: 0,
        pan: 0,
      },
      {
        waveform: "triangle",
        frequency: 0,
        range: "4",
        volume: 0.7,
        detune: 0,
        pan: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 0,
      contourAmount: 0,
      type: "lowpass",
    },
    envelope: {
      attack: 0.1,
      decay: 0.1,
      sustain: 0.7,
      release: 0.3,
    },
    lfo: {
      rate: 5,
      depth: 0.5,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 0,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 94,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 58,
      time: 0.3,
      feedback: 13,
    },
  },
  "Custom Moog": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
        pan: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 7,
        pan: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.4,
        detune: -7,
        pan: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1000,
      resonance: 0.5,
      contourAmount: 0.5,
      type: "lowpass",
    },
    envelope: {
      attack: 0.1,
      decay: 0.3,
      sustain: 0.7,
      release: 0.5,
    },
    lfo: {
      rate: 5,
      depth: 0.3,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 0,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Warm Pad": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.3,
    oscillators: [
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 7,
        range: "8",
        volume: 0.5,
        detune: 3,
      },
      {
        waveform: "sine",
        frequency: -7,
        range: "8",
        volume: 0.3,
        detune: -3,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 1,
      contourAmount: 0.3,
      type: "lowpass",
    },
    envelope: {
      attack: 0.5,
      decay: 0.8,
      sustain: 0.8,
      release: 1.2,
    },
    lfo: {
      rate: 2,
      depth: 0.2,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 40,
      decay: 2.5,
      eq: 60,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 20,
      time: 0.4,
      feedback: 0.3,
    },
  },
  "Warm Pad 2": {
    octave: 1,
    modMix: 50,
    modWheel: 50,
    glide: 0.3,
    oscillators: [
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 0,
        pan: 0,
      },
      {
        waveform: "sine",
        frequency: 7,
        range: "2",
        volume: 0.7,
        detune: 3,
        pan: 0.42,
      },
      {
        waveform: "sawtooth",
        frequency: -7,
        range: "16",
        volume: 0.7,
        detune: -3,
        pan: -0.42,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 0.34,
      contourAmount: 0.3,
      type: "lowpass",
    },
    envelope: {
      attack: 0.5,
      decay: 0.8,
      sustain: 0.8,
      release: 1.2,
    },
    lfo: {
      rate: 2,
      depth: 0.2,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 40,
      decay: 2.5,
      eq: 60,
    },
    distortion: {
      outputGain: 28,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 20,
      time: 0.4,
      feedback: 0.3,
    },
  },
  "Bass Lead": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.1,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "16",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "16",
        volume: 0.6,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "16",
        volume: 0.3,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 500,
      resonance: 0.3,
      contourAmount: 0.7,
      type: "lowpass",
    },
    envelope: {
      attack: 0.01,
      decay: 0.2,
      sustain: 0.6,
      release: 0.3,
    },
    lfo: {
      rate: 8,
      depth: 0.4,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 10,
      decay: 1.0,
      eq: 40,
    },
    distortion: {
      outputGain: 20,
      lowEQ: 60,
      highEQ: 40,
    },
    delay: {
      amount: 0,
      time: 0.3,
      feedback: 0.3,
    },
  },
  Pluck: {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "square",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 12,
        range: "8",
        volume: 0.4,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 19,
        range: "8",
        volume: 0.2,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 0.2,
      contourAmount: 0.8,
      type: "lowpass",
    },
    envelope: {
      attack: 0.01,
      decay: 0.1,
      sustain: 0.1,
      release: 0.2,
    },
    lfo: {
      rate: 0,
      depth: 0,
      waveform: "sine",
      routing: {
        filterCutoff: false,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 30,
      decay: 1.0,
      eq: 50,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 15,
      time: 0.2,
      feedback: 0.2,
    },
  },
  "Brass Lead": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.2,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 5,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.5,
        detune: -5,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1500,
      resonance: 0.4,
      contourAmount: 0.6,
      type: "lowpass",
    },
    envelope: {
      attack: 0.05,
      decay: 0.2,
      sustain: 0.8,
      release: 0.4,
    },
    lfo: {
      rate: 6,
      depth: 0.3,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 15,
      decay: 1.2,
      eq: 45,
    },
    distortion: {
      outputGain: 10,
      lowEQ: 55,
      highEQ: 45,
    },
    delay: {
      amount: 10,
      time: 0.3,
      feedback: 0.2,
    },
  },
  "Ambient Pad": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.4,
    oscillators: [
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 4,
        range: "8",
        volume: 0.6,
        detune: 2,
      },
      {
        waveform: "sine",
        frequency: 7,
        range: "8",
        volume: 0.4,
        detune: -2,
      },
    ],
    noise: {
      volume: 0.1,
      pan: 0,
      type: "pink",
      tone: 220,
      sync: true,
    },
    filter: {
      cutoff: 3000,
      resonance: 0.2,
      contourAmount: 0.4,
      type: "lowpass",
    },
    envelope: {
      attack: 1.0,
      decay: 1.5,
      sustain: 0.9,
      release: 2.0,
    },
    lfo: {
      rate: 1,
      depth: 0.4,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: true,
      },
    },
    reverb: {
      amount: 60,
      decay: 3.0,
      eq: 70,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 30,
      time: 0.6,
      feedback: 0.4,
    },
  },
  "Acid Bass": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.1,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "16",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "16",
        volume: 0.6,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "16",
        volume: 0.3,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 800,
      resonance: 0.9,
      contourAmount: 0.8,
      type: "lowpass",
    },
    envelope: {
      attack: 0.01,
      decay: 0.1,
      sustain: 0.5,
      release: 0.2,
    },
    lfo: {
      rate: 12,
      depth: 0.5,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 5,
      decay: 0.8,
      eq: 30,
    },
    distortion: {
      outputGain: 15,
      lowEQ: 70,
      highEQ: 30,
    },
    delay: {
      amount: 5,
      time: 0.2,
      feedback: 0.2,
    },
  },
  "String Ensemble": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.2,
    oscillators: [
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 3,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: -3,
      },
    ],
    noise: {
      volume: 0.05,
      pan: 0,
      type: "pink",
      tone: 880,
      sync: true,
    },
    filter: {
      cutoff: 2500,
      resonance: 0.3,
      contourAmount: 0.5,
      type: "lowpass",
    },
    envelope: {
      attack: 0.3,
      decay: 0.5,
      sustain: 0.9,
      release: 1.0,
    },
    lfo: {
      rate: 4,
      depth: 0.2,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 50,
      decay: 2.0,
      eq: 60,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 25,
      time: 0.5,
      feedback: 0.3,
    },
  },
  "Synth Lead": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.15,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 4,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.5,
        detune: -4,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 0.6,
      contourAmount: 0.7,
      type: "lowpass",
    },
    envelope: {
      attack: 0.02,
      decay: 0.2,
      sustain: 0.7,
      release: 0.3,
    },
    lfo: {
      rate: 7,
      depth: 0.4,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.2,
      eq: 50,
    },
    distortion: {
      outputGain: 10,
      lowEQ: 60,
      highEQ: 40,
    },
    delay: {
      amount: 15,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Glide Lead": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 4.4,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 3,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.5,
        detune: -3,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1800,
      resonance: 0.4,
      contourAmount: 0.6,
      type: "lowpass",
    },
    envelope: {
      attack: 0.05,
      decay: 0.2,
      sustain: 0.8,
      release: 0.4,
    },
    lfo: {
      rate: 5,
      depth: 0.3,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 15,
      decay: 1.2,
      eq: 45,
    },
    distortion: {
      outputGain: 5,
      lowEQ: 55,
      highEQ: 45,
    },
    delay: {
      amount: 10,
      time: 0.3,
      feedback: 0.2,
    },
  },
  "Noise Pad": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.4,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.3,
        detune: 0,
      },
    ],
    noise: {
      volume: 0.4,
      pan: 0,
      type: "pink",
      tone: 220,
      sync: true,
    },
    filter: {
      cutoff: 1000,
      resonance: 0.3,
      contourAmount: 0.5,
      type: "lowpass",
    },
    envelope: {
      attack: 0.8,
      decay: 1.2,
      sustain: 0.7,
      release: 1.5,
    },
    lfo: {
      rate: 2,
      depth: 0.4,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: true,
      },
    },
    reverb: {
      amount: 50,
      decay: 2.5,
      eq: 60,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 25,
      time: 0.5,
      feedback: 0.3,
    },
  },
  "Stereo Spread": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
        pan: -0.8,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
        pan: 0.8,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 0,
        pan: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 0.4,
      contourAmount: 0.5,
      type: "lowpass",
    },
    envelope: {
      attack: 0.1,
      decay: 0.3,
      sustain: 0.8,
      release: 0.5,
    },
    lfo: {
      rate: 4,
      depth: 0.3,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 30,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 20,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Wide Range": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "32",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "16",
        volume: 0.7,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.5,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1500,
      resonance: 0.5,
      contourAmount: 0.6,
      type: "lowpass",
    },
    envelope: {
      attack: 0.05,
      decay: 0.2,
      sustain: 0.7,
      release: 0.3,
    },
    lfo: {
      rate: 6,
      depth: 0.4,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.2,
      eq: 45,
    },
    distortion: {
      outputGain: 10,
      lowEQ: 60,
      highEQ: 40,
    },
    delay: {
      amount: 15,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Filter Sweep": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 5,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.4,
        detune: -5,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 0.8,
      contourAmount: 0.9,
      type: "lowpass",
    },
    envelope: {
      attack: 0.01,
      decay: 0.5,
      sustain: 0.3,
      release: 0.8,
    },
    lfo: {
      rate: 0.5,
      depth: 0.7,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 25,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 5,
      lowEQ: 55,
      highEQ: 45,
    },
    delay: {
      amount: 20,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Modulation Madness": {
    octave: 0,
    modMix: 80,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.4,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1500,
      resonance: 0.6,
      contourAmount: 0.7,
      type: "lowpass",
    },
    envelope: {
      attack: 0.1,
      decay: 0.3,
      sustain: 0.7,
      release: 0.5,
    },
    lfo: {
      rate: 8,
      depth: 0.6,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: true,
        oscillatorPitch: true,
        oscillatorVolume: true,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.2,
      eq: 45,
    },
    distortion: {
      outputGain: 10,
      lowEQ: 55,
      highEQ: 45,
    },
    delay: {
      amount: 15,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "High Pass Lead": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.5,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1000,
      resonance: 0.6,
      contourAmount: 0.5,
      type: "highpass",
    },
    envelope: {
      attack: 0.05,
      decay: 0.2,
      sustain: 0.7,
      release: 0.3,
    },
    lfo: {
      rate: 6,
      depth: 0.4,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.2,
      eq: 45,
    },
    distortion: {
      outputGain: 10,
      lowEQ: 60,
      highEQ: 40,
    },
    delay: {
      amount: 15,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Band Pass Pad": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0.3,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 1.0,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 1.0,
        detune: 3,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 1.0,
        detune: -3,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 1500,
      resonance: 0.8,
      contourAmount: 0.4,
      type: "lowpass",
    },
    envelope: {
      attack: 0.5,
      decay: 0.8,
      sustain: 0.8,
      release: 1.2,
    },
    lfo: {
      rate: 2,
      depth: 0.3,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 40,
      decay: 2.0,
      eq: 55,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 25,
      time: 0.4,
      feedback: 0.3,
    },
  },
  "Notch Sweep": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.9,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.7,
        detune: 5,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.5,
        detune: -5,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 2000,
      resonance: 0.8,
      contourAmount: 0.7,
      type: "notch",
    },
    envelope: {
      attack: 0.01,
      decay: 0.3,
      sustain: 0.5,
      release: 0.6,
    },
    lfo: {
      rate: 0.5,
      depth: 0.6,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 25,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 5,
      lowEQ: 55,
      highEQ: 45,
    },
    delay: {
      amount: 20,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Filter Stack": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 0.8,
        detune: 0,
      },
      {
        waveform: "square",
        frequency: 0,
        range: "8",
        volume: 0.6,
        detune: 0,
      },
      {
        waveform: "sine",
        frequency: 0,
        range: "8",
        volume: 0.4,
        detune: 0,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 3000,
      resonance: 0.9,
      contourAmount: 0.8,
      type: "highpass",
    },
    envelope: {
      attack: 0.05,
      decay: 0.2,
      sustain: 0.7,
      release: 0.3,
    },
    lfo: {
      rate: 4,
      depth: 0.5,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: false,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 20,
      decay: 1.2,
      eq: 45,
    },
    distortion: {
      outputGain: 15,
      lowEQ: 70,
      highEQ: 30,
    },
    delay: {
      amount: 15,
      time: 0.3,
      feedback: 0.3,
    },
  },
  "Vocal Band": {
    octave: 0,
    modMix: 50,
    modWheel: 50,
    glide: 0,
    oscillators: [
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 1.0,
        detune: 0,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 1.0,
        detune: 2,
      },
      {
        waveform: "sawtooth",
        frequency: 0,
        range: "8",
        volume: 1.0,
        detune: -2,
      },
    ],
    noise: {
      volume: 0,
      pan: 0,
      type: "white",
      tone: 440,
      sync: false,
    },
    filter: {
      cutoff: 4000,
      resonance: 0.1,
      contourAmount: 0.6,
      type: "bandpass",
    },
    envelope: {
      attack: 0.1,
      decay: 0.3,
      sustain: 0.7,
      release: 0.4,
    },
    lfo: {
      rate: 5,
      depth: 0.2,
      waveform: "sine",
      routing: {
        filterCutoff: true,
        filterResonance: false,
        oscillatorPitch: true,
        oscillatorVolume: false,
      },
    },
    reverb: {
      amount: 30,
      decay: 1.5,
      eq: 50,
    },
    distortion: {
      outputGain: 0,
      lowEQ: 50,
      highEQ: 50,
    },
    delay: {
      amount: 20,
      time: 0.3,
      feedback: 0.3,
    },
  },
};
